[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
http_port = 8069
proxy_mode = True
db_host = ${HOST}
db_port = 5432
db_user = ${USER}
db_password = ${PASSWORD}
db_name = ${DATABASE}
