[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = False
db_port = False
db_user = False
db_password = False
db_name = False
http_port = 8069
proxy_mode = True
